version: '3'

services:
  sentinel-3:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=500
      - SENTINEL_QUORUM=2
      - REDIS_MASTER_PASSWORD=CHANGE PASS
    ports:
      - '26379-26381:26379'
