version: '3'

services:
  redis-slave:
    container_name: redis-slave
    image: redis:${IMAGE_VERSION}
    command: redis-server --slaveof ${REDIS_MASTER_HOST} 6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_MASTER_PASSWORD=CHANGE PASS
      - REDIS_PASSWORD=CHANGE PASS
    ports:
      - 6379:6379

  sentinel-2:
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=500
      - SENTINEL_QUORUM=2
      - REDIS_MASTER_PASSWORD=CHANGE PASS
    ports:
      - '26379-26381:26379'
    depends_on:
      - redis-slave
  