version: '3'

services:
  redis-master:
    container_name: redis-master
    image: redis:${IMAGE_VERSION}
    command: redis-server
    ports:
     - 6379:6379
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=CHANGE PASS

  sentinel-1:
    container_name: sentinel-1
    build: sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=500
      - SENTINEL_QUORUM=2
      - REDIS_MASTER_PASSWORD=CHANGE PASS
    ports:
      - '26379-26381:26379'
    depends_on:
      - redis-master